<?php

namespace Container1lxxWi4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCSB2GGestionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CSB2GGestionController' shared autowired service.
     *
     * @return \App\Controller\CSB2GGestionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\CSB2GGestionController.php';

        $container->services['App\\Controller\\CSB2GGestionController'] = $instance = new \App\Controller\CSB2GGestionController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\CSB2GGestionController', $container));

        return $instance;
    }
}
