<?php

namespace Container1lxxWi4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransferTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TransferType' shared autowired service.
     *
     * @return \App\Form\TransferType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\TransferType.php';

        return $container->privates['App\\Form\\TransferType'] = new \App\Form\TransferType();
    }
}
